direction: right

source_vm: "Source VM"
rivermeadow_saas: "RiverMeadow SaaS"
pre_migration: "Pre-Migration"
migration: "Migration"
post_migration: "Post-Migration"
target_vm: "Target VM"

source_vm -> pre_migration -> rivermeadow_saas -> migration -> post_migration -> target_vm