direction: right

source: "Source OS Environment"
target: "Target OS Cloud"
rivermeadow: "RiverMeadow SaaS"
os_discovery: "OS Discovery"
os_migration: "OS Migration"

source -> os_discovery -> rivermeadow -> os_migration -> target