direction: right
source: {
  label: "Source Environment"
  shape: cloud
  style.fill: lightyellow
}
target: {
  label: "Target Environment"
  shape: cloud
  style.fill: lightblue
}
rivermeadow: {
  label: "RiverMeadow"
  shape: rectangle
  style.fill: "#D0FFC0"
}
source -> rivermeadow -> target
