# RiverMeadow Cloud Migration Process

direction: right

title: {
  label: "RiverMeadow Cloud Migration Process"
  near: top-center
  shape: text
  style.fontSize: 24
  style.bold: true
}

source: {
  label: "Source Environment"
  shape: cloud
  style.fill: lightyellow
}

target: {
  label: "Target Cloud"
  shape: cloud
  style.fill: lightblue
}

rivermeadow: {
  label: "RiverMeadow SaaS"
  shape: rectangle
  style.fill: "#D0FFC0"
}

discovery: {
  label: "Discovery"
  shape: rectangle
}

migration: {
  label: "Migration"
  shape: rectangle
}

source -> discovery -> rivermeadow -> migration -> target